snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: uyuyzkj-gs92073

      # User/password auth
      user: praveen11001
      password : admin@123G

      role: ACCOUNTADMIN
      database: demo_db_try
      warehouse: COMPUTE_WH
      schema: demo_schema
      threads: 10
      client_session_keep_alive: false
      query_tag: select * from db_manage.demo_schema.shop_demo

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)